### ISSUE TITLE
DangerDeckActivity crashes on Samsung S6

### ISSUE THREAD

**Issue by kuhrusty** [kuhrusty/MorbadScorepad#16]
vaderizer reports that the Danger deck activity crashes on one of his devices (Samsung S6 Active phone running Android 7.0).  I am able to reproduce this both in Samsung Remote Test Lab and on my box in a virtual device:

    E/AndroidRuntime: FATAL EXCEPTION: main
        Process: com.kuhrusty.morbadscorepad, PID: 6509
        java.lang.RuntimeException: Canvas: trying to draw too large(157286400bytes) bitmap.
            at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:260)
            at android.graphics.Canvas.drawBitmap(Canvas.java:1415)
            at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
            at android.widget.ImageView.onDraw(ImageView.java:1286)
            ...

`app/src/main/res/drawable/dangerbg.jpg` *is* 1280x1920, but that's less than the size of the S6's screen; 157286400 bytes / (1280 * 1920) = 64, or 4 * 4 * 4; I suspect what's happening (at least on that device) is, the image is being treated as mdpi, and is being scaled up 4x to xxxhdpi, so the first thing to try is moving dangerbg.jpg into drawable-xxxhdpi.

**Comment by kuhrusty** [comment]
Oh yeah, see [more blather about drawables](https://github.com/kuhrusty/MorbadScorepad/blob/master/CONTRIBUTING.md#more-blather-about-drawables) in CONTRIBUTING.md.

**Comment by sgbeal** [comment]
It's _magic_.
